/** 领域事件类型。事件一经追加不可变；状态修正只能通过新事件表达。 */
export const EVT = {
  COUNTRY_REGISTERED: 'COUNTRY_REGISTERED',
  ACTIVITY_REGISTERED: 'ACTIVITY_REGISTERED',
  ROLE_REGISTERED: 'ROLE_REGISTERED',
  RULES_PUBLISHED: 'RULES_PUBLISHED',
  ENTITY_ONBOARDED: 'ENTITY_ONBOARDED',
  EVIDENCE_IMPORTED: 'EVIDENCE_IMPORTED',
  EVIDENCE_SUPERSEDED: 'EVIDENCE_SUPERSEDED',
  IMPORT_DEDUPLICATED: 'IMPORT_DEDUPLICATED',
  EXEMPTION_GRANTED: 'EXEMPTION_GRANTED',
  EXEMPTION_REVOKED: 'EXEMPTION_REVOKED',
  REQUIREMENT_REVIEWED: 'REQUIREMENT_REVIEWED',
  NOTIFICATION_CREATED: 'NOTIFICATION_CREATED',
  NOTIFICATION_READ: 'NOTIFICATION_READ',
  OPENING_REVIEW_COMPLETED: 'OPENING_REVIEW_COMPLETED',
};

export const EVIDENCE_SOURCES = ['CONTRACT', 'BANK', 'ADVISOR'];
